In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [16]:
def convert_y(dataY):
    y = []
    for i in range (len(dataY)):
        if(dataY[i] > 50):
            y.append(0)
        else:
            y.append(1)
    return np.array(y)

In [17]:
dataX = pd.read_csv('./datasets/spotofy_music_normalized.csv')
dataY = pd.read_csv('./datasets/spotofy_music_labels.csv')
dataY_multi = pd.read_csv('./datasets/spotofy_music_labels.csv')
dataY.head()

Rank
0     1
1     2
2     3
3     4
4     2

In [18]:
cut_labels = [1, 2, 3, 4, 5]
cut_bins = [0, 40, 80, 120, 160, 200]
dataY_multi['Rank'] = pd.cut(dataY_multi['Rank'], bins=cut_bins, labels=cut_labels)

In [19]:
m = len(dataX) # Number of  examples
X = np.array(dataX)
Y = np.array(dataY)
Y1= np.array(dataY_multi)
Y = convert_y(Y)
Y = np.array(Y)
Y_multi = []
for i in range (len(Y1)):
    Y_multi.append(Y1[i][0])
Y_multi = np.array(Y_multi)

In [20]:
def accuracy(Y,y_pred):
    return np.sum(y_pred==Y)/len(Y)


In [22]:
kf = KFold(n_splits=5)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    model = SGDClassifier(alpha=0.001, penalty='l2')
    model.fit(X_train, y_train)
    y_predicted = model.predict(X_test)
    confusionM = confusion_matrix(y_test,y_predicted )
    print("Confusion Matrix is :")
    print(confusionM)
    print()
    print("Accuracy is:",accuracy(y_test, y_predicted))
    TP = confusionM[1][1]
    TN = confusionM[0][0]
    FN = confusionM[1][0]
    FP = confusionM[0][1]
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    f1_score = 2*((precision* recall)/ (precision+recall))
    print("Precison is:", precision)
    print("Recall is:", recall)
    print("F1-score of SGD is:", f1_score)
    print()



Confusion Matrix is :
[[536  44]
 [216  54]]

Accuracy is: 0.6941176470588235
Precison is: 0.5510204081632653
Recall is: 0.2
F1-score of SGD is: 0.29347826086956524

Confusion Matrix is :
[[501  39]
 [256  54]]

Accuracy is: 0.6529411764705882
Precison is: 0.5806451612903226
Recall is: 0.17419354838709677
F1-score of SGD is: 0.2679900744416873

Confusion Matrix is :
[[578  10]
 [233  28]]

Accuracy is: 0.7137809187279152
Precison is: 0.7368421052631579
Recall is: 0.10727969348659004
F1-score of SGD is: 0.18729096989966557

Confusion Matrix is :
[[529  26]
 [268  26]]

Accuracy is: 0.6537102473498233
Precison is: 0.5
Recall is: 0.08843537414965986
F1-score of SGD is: 0.15028901734104047

Confusion Matrix is :
[[538  18]
 [247  46]]

Accuracy is: 0.6878680800942285
Precison is: 0.71875
Recall is: 0.15699658703071673
F1-score of SGD is: 0.25770308123249297



In [25]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
kf = KFold(n_splits=5)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y_multi[train_index], Y_multi[test_index]
    model = OneVsRestClassifier(SGDClassifier(alpha=0.001, penalty='l2'))
    model.fit(X_train, y_train)
    y_predicted = model.predict(X_test)
    confusionM = confusion_matrix(y_test,y_predicted )
    print("Confusion Matrix is :")
    print(confusionM)
    print()
    print("Accuracy is:",accuracy(y_test, y_predicted))
    TP = confusionM[1][1]
    TN = confusionM[0][0]
    FN = confusionM[1][0]
    FP = confusionM[0][1]
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    f1_score = 2*((precision* recall)/ (precision+recall))
    print("Precison is:", precision)
    print("Recall is:", recall)
    print("F1-score of SGD is:", f1_score)
    print()


Confusion Matrix is :
[[130  29  30  20  27]
 [ 66  19  22  23  28]
 [ 54  17  31  29  32]
 [ 59  21  26  30  17]
 [ 48  12  27  21  32]]

Accuracy is: 0.2847058823529412
Precison is: 0.3958333333333333
Recall is: 0.2235294117647059
F1-score of SGD is: 0.2857142857142857

Confusion Matrix is :
[[181  25  32   9  17]
 [110  27  27   4  21]
 [ 82  25  20   4  18]
 [ 71  21  23   3  23]
 [ 40  22  23   6  16]]

Accuracy is: 0.29058823529411765
Precison is: 0.5192307692307693
Recall is: 0.19708029197080293
F1-score of SGD is: 0.2857142857142857

Confusion Matrix is :
[[112  39  22   7  48]
 [ 66  35  26  10  34]
 [ 42  35  11   7  34]
 [ 55  47  14   7  47]
 [ 40  46  18   8  39]]

Accuracy is: 0.24028268551236748
Precison is: 0.47297297297297297
Recall is: 0.3465346534653465
F1-score of SGD is: 0.4

Confusion Matrix is :
[[132  63  12  16  18]
 [100  62  20  17  15]
 [ 50  54  24   9  24]
 [ 30  41  16  20  11]
 [ 43  33  17  12  10]]

Accuracy is: 0.2921083627797409
Precison is: 0.496
Re