In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix


In [8]:
def convert_y(dataY):
    y = []
    for i in range (len(dataY)):
        if(dataY[i] > 100):
            y.append(0)
        else:
            y.append(1)
    return np.array(y)

In [9]:
dataX = pd.read_csv('./datasets/spotofy_music_normalized.csv')
dataX.head()
m = len(dataX) # Number of  examples
X = np.array(dataX)

dataY = pd.read_csv('./datasets/spotofy_music_labels.csv')
dataY.head()
Y = np.array(dataY)
Y = convert_y(Y)
Y = np.array(Y)
print(Y)

[1 1 1 ... 0 0 0]


In [10]:
def accuracy(Y,y_pred):
    return np.sum(y_pred==Y)/len(Y)


In [12]:
kf = KFold(n_splits=5)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    model = SGDClassifier(alpha=0.001, penalty='l2')
    model.fit(X_train, y_train)
    y_predicted = model.predict(X_test)
    confusionM = confusion_matrix(y_test,y_predicted )
    print("Confusion Matrix is :")
    print(confusionM)
    print()
    print("Accuracy is:",accuracy(y_test, y_predicted))
    TP = confusionM[1][1]
    TN = confusionM[0][0]
    FN = confusionM[1][0]
    FP = confusionM[0][1]
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    f1_score = 2*((precision* recall)/ (precision+recall))
    print("Precison is:", precision)
    print("Recall is:", recall)
    print("F1-score of SGD is:", f1_score)
    print()



Confusion Matrix is :
[[130 249]
 [113 358]]

Accuracy is: 0.5741176470588235
Precison is: 0.5897858319604613
Recall is: 0.7600849256900213
F1-score of SGD is: 0.6641929499072358

Confusion Matrix is :
[[118 214]
 [101 417]]

Accuracy is: 0.6294117647058823
Precison is: 0.6608557844690967
Recall is: 0.805019305019305
F1-score of SGD is: 0.7258485639686684

Confusion Matrix is :
[[ 78 311]
 [ 64 396]]

Accuracy is: 0.558303886925795
Precison is: 0.5601131541725601
Recall is: 0.8608695652173913
F1-score of SGD is: 0.6786632390745502

Confusion Matrix is :
[[ 84 240]
 [102 423]]

Accuracy is: 0.5971731448763251
Precison is: 0.6380090497737556
Recall is: 0.8057142857142857
F1-score of SGD is: 0.712121212121212

Confusion Matrix is :
[[ 75 260]
 [ 71 443]]

Accuracy is: 0.6101295641931684
Precison is: 0.6301564722617354
Recall is: 0.8618677042801557
F1-score of SGD is: 0.7280197206244865

