In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix


In [40]:
def convert_y(dataY):
    y = []
    for i in range (len(dataY)):
        if(dataY[i] > 50):
            y.append(0)
        else:
            y.append(1)
    return np.array(y)

In [41]:
dataX = pd.read_csv('./datasets/spotofy_music_normalized.csv')
dataX.head()
m = len(dataX) # Number of  examples
X = np.array(dataX)

dataY = pd.read_csv('./datasets/spotofy_music_labels.csv')
dataY.head()
Y = np.array(dataY)
Y = convert_y(Y)
Y = np.array(Y)
print(Y)

[1 1 1 ... 0 0 0]


In [42]:
def accuracy(Y,y_pred):
    return np.sum(y_pred==Y)/len(Y)


In [43]:
kf = KFold(n_splits=5)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    model = SGDClassifier(alpha=0.001, penalty='l2')
    model.fit(X_train, y_train)
    y_predicted = model.predict(X_test)
    confusionM = confusion_matrix(y_test,y_predicted )
    print("Confusion Matrix is :")
    print(confusionM)
    print()
    print("Accuracy is:",accuracy(y_test, y_predicted))
    TP = confusionM[1][1]
    TN = confusionM[0][0]
    FN = confusionM[1][0]
    FP = confusionM[0][1]
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    f1_score = 2*((precision* recall)/ (precision+recall))
    print("Precison is:", precision)
    print("Recall is:", recall)
    print("F1-score of SGD is:", f1_score)
    print()



Confusion Matrix is :
[[535  45]
 [223  47]]

Accuracy is: 0.6847058823529412
Precison is: 0.5108695652173914
Recall is: 0.17407407407407408
F1-score of SGD is: 0.2596685082872928

Confusion Matrix is :
[[532   8]
 [283  27]]

Accuracy is: 0.6576470588235294
Precison is: 0.7714285714285715
Recall is: 0.08709677419354839
F1-score of SGD is: 0.1565217391304348

Confusion Matrix is :
[[584   4]
 [240  21]]

Accuracy is: 0.7126030624263839
Precison is: 0.84
Recall is: 0.08045977011494253
F1-score of SGD is: 0.14685314685314685

Confusion Matrix is :
[[528  27]
 [265  29]]

Accuracy is: 0.6560659599528857
Precison is: 0.5178571428571429
Recall is: 0.09863945578231292
F1-score of SGD is: 0.1657142857142857

Confusion Matrix is :
[[546  10]
 [269  24]]

Accuracy is: 0.6713780918727915
Precison is: 0.7058823529411765
Recall is: 0.08191126279863481
F1-score of SGD is: 0.14678899082568805

