### Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

C:\Python39\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Python39\lib\site-packages\numpy\.libs\libopenblas.JPIJNSWNNAN3CE6LLI5FWSPHUT2VXMTH.gfortran-win_amd64.dll
C:\Python39\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


### Preprocessing

In [2]:
# Defining labels for ranking scores:
def convert_y(dataY):
    y = []
    for i in range (len(dataY)):
        if(dataY[i] > 50):
            y.append(0)
        else:
            y.append(1)
    return np.array(y)

In [3]:
# Reading data:
dataX = pd.read_csv('../datasets/spotofy_music_normalized.csv')
dataY = pd.read_csv('../datasets/spotofy_music_labels.csv')
dataY_multi = pd.read_csv('../datasets/spotofy_music_labels.csv')
dataY.head()

Rank
0     1
1     2
2     3
3     4
4     2

In [4]:
cut_labels = [1, 2, 3, 4, 5]
cut_bins = [0, 40, 80, 120, 160, 200]
dataY_multi['Rank'] = pd.cut(dataY_multi['Rank'], bins=cut_bins, labels=cut_labels)

In [5]:
m = len(dataX) # Number of  examples
X = np.array(dataX)
Y = np.array(dataY)
Y1= np.array(dataY_multi)
Y = convert_y(Y)
Y = np.array(Y)
Y_multi = []
for i in range (len(Y1)):
    Y_multi.append(Y1[i][0])
Y_multi = np.array(Y_multi)

In [6]:
def accuracy(Y,y_pred):
    return np.sum(y_pred==Y)/len(Y)


### Binary Classification

In [7]:
kf = KFold(n_splits=5)
cnt = 0
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    model = SGDClassifier(alpha=0.001, penalty='l2')
    model.fit(X_train, y_train)
    cnt += 1
    np.savetxt('../weights/logistic_split_'+str(cnt)+'.txt', model.coef_, delimiter=" ", fmt="%f")
    y_predicted = model.predict(X_test)
    confusionM = confusion_matrix(y_test,y_predicted )

    print("Confusion Matrix is :")
    print(confusionM)
    print()
    print("Accuracy is:",accuracy(y_test, y_predicted))
    TP = confusionM[1][1]
    TN = confusionM[0][0]
    FN = confusionM[1][0]
    FP = confusionM[0][1]
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    f1_score = 2*((precision* recall)/ (precision+recall))
    print("Precison is:", precision)
    print("Recall is:", recall)
    print("F1-score of SGD is:", f1_score)
    print()



Confusion Matrix is :
[[519  61]
 [215  55]]

Accuracy is: 0.6752941176470588
Precison is: 0.47413793103448276
Recall is: 0.2037037037037037
F1-score of SGD is: 0.28497409326424866

Confusion Matrix is :
[[504  36]
 [251  59]]

Accuracy is: 0.6623529411764706
Precison is: 0.6210526315789474
Recall is: 0.19032258064516128
F1-score of SGD is: 0.291358024691358

Confusion Matrix is :
[[587   1]
 [250  11]]

Accuracy is: 0.7043580683156655
Precison is: 0.9166666666666666
Recall is: 0.0421455938697318
F1-score of SGD is: 0.08058608058608059

Confusion Matrix is :
[[500  55]
 [241  53]]

Accuracy is: 0.6513545347467609
Precison is: 0.49074074074074076
Recall is: 0.18027210884353742
F1-score of SGD is: 0.26368159203980096

Confusion Matrix is :
[[528  28]
 [227  66]]

Accuracy is: 0.6996466431095406
Precison is: 0.7021276595744681
Recall is: 0.22525597269624573
F1-score of SGD is: 0.34108527131782945



### Multiclass

In [8]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
kf = KFold(n_splits=5)
cnt = 0
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y_multi[train_index], Y_multi[test_index]
    model = OneVsRestClassifier(SGDClassifier(alpha=0.001, penalty='l2'))
    model.fit(X_train, y_train)
    cnt += 1
    np.savetxt('../weights/ovr_split_'+str(cnt)+'.txt', model.coef_, delimiter=" ", fmt="%f")
    y_predicted = model.predict(X_test)
    confusionM = confusion_matrix(y_test,y_predicted )
    print("Confusion Matrix is :")
    print(confusionM)
    print()
    print("Accuracy is:",accuracy(y_test, y_predicted))
    TP = confusionM[1][1]
    TN = confusionM[0][0]
    FN = confusionM[1][0]
    FP = confusionM[0][1]
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    f1_score = 2*((precision* recall)/ (precision+recall))
    print("Precison is:", precision)
    print("Recall is:", recall)
    print("F1-score of SGD is:", f1_score)
    print()


Confusion Matrix is :
[[103  60  23  36  14]
 [ 59  37  23  26  13]
 [ 50  46  22  37   8]
 [ 43  42  12  40  16]
 [ 35  42   9  46   8]]

Accuracy is: 0.24705882352941178
Precison is: 0.38144329896907214
Recall is: 0.3854166666666667
F1-score of SGD is: 0.38341968911917096

Confusion Matrix is :
[[165  26  22  11  40]
 [ 97  34  22   5  31]
 [ 63  27  18   8  33]
 [ 71  22  17   8  23]
 [ 38  22  15   7  25]]

Accuracy is: 0.29411764705882354
Precison is: 0.5666666666666667
Recall is: 0.2595419847328244
F1-score of SGD is: 0.35602094240837695

Confusion Matrix is :
[[128  19  26  29  26]
 [ 60  18  30  31  32]
 [ 46  13  24  24  22]
 [ 52  21  34  25  38]
 [ 43  14  33  23  38]]

Accuracy is: 0.2744405182567727
Precison is: 0.4864864864864865
Recall is: 0.23076923076923078
F1-score of SGD is: 0.3130434782608696

Confusion Matrix is :
[[145  25   8  48  15]
 [ 95  41  14  42  22]
 [ 54  27  10  43  27]
 [ 17  27   9  44  21]
 [ 28  31   5  33  18]]

Accuracy is: 0.303886925795053
Preci

C:\Python39\lib\site-packages\sklearn\utils\deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26). If you observe this warning while using RFE or SelectFromModel, use the importance_getter parameter instead.
  warnings.warn(msg, category=FutureWarning)
C:\Python39\lib\site-packages\sklearn\utils\deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26). If you observe this warning while using RFE or SelectFromModel, use the importance_getter parameter instead.
  warnings.warn(msg, category=FutureWarning)
C:\Python39\lib\site-packages\sklearn\utils\deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26). If you observe this warning while using RFE or SelectFromModel, use the importance_getter parameter instead.
  warnings.warn(msg, category=FutureWarning)
C:\Python39\lib\sit