In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

C:\Python39\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Python39\lib\site-packages\numpy\.libs\libopenblas.JPIJNSWNNAN3CE6LLI5FWSPHUT2VXMTH.gfortran-win_amd64.dll
C:\Python39\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
def convert_y(dataY):
    y = []
    for i in range (len(dataY)):
        if(dataY[i] > 50):
            y.append(0)
        else:
            y.append(1)
    return np.array(y)

In [3]:
dataX = pd.read_csv('../datasets/spotofy_music_normalized.csv')
dataY = pd.read_csv('../datasets/spotofy_music_labels.csv')
dataY_multi = pd.read_csv('../datasets/spotofy_music_labels.csv')
dataY.head()

Rank
0     1
1     2
2     3
3     4
4     2

In [4]:
cut_labels = [1, 2, 3, 4, 5]
cut_bins = [0, 40, 80, 120, 160, 200]
dataY_multi['Rank'] = pd.cut(dataY_multi['Rank'], bins=cut_bins, labels=cut_labels)

In [5]:
m = len(dataX) # Number of  examples
X = np.array(dataX)
Y = np.array(dataY)
Y1= np.array(dataY_multi)
Y = convert_y(Y)
Y = np.array(Y)
Y_multi = []
for i in range (len(Y1)):
    Y_multi.append(Y1[i][0])
Y_multi = np.array(Y_multi)

In [6]:
def accuracy(Y,y_pred):
    return np.sum(y_pred==Y)/len(Y)


### Binary Classification

In [9]:
kf = KFold(n_splits=5)
cnt = 0
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    model = SGDClassifier(alpha=0.001, penalty='l2')
    model.fit(X_train, y_train)
    cnt +=1
    np.savetxt('logistic_split_'+str(cnt)+'.txt', model.coef_, delimiter=" ", fmt="%f")
    y_predicted = model.predict(X_test)
    confusionM = confusion_matrix(y_test,y_predicted )
    print("Confusion Matrix is :")
    print(confusionM)
    print()
    print("Accuracy is:",accuracy(y_test, y_predicted))
    TP = confusionM[1][1]
    TN = confusionM[0][0]
    FN = confusionM[1][0]
    FP = confusionM[0][1]
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    f1_score = 2*((precision* recall)/ (precision+recall))
    print("Precison is:", precision)
    print("Recall is:", recall)
    print("F1-score of SGD is:", f1_score)
    print()



Confusion Matrix is :
[[528  52]
 [212  58]]

Accuracy is: 0.6894117647058824
Precison is: 0.5272727272727272
Recall is: 0.21481481481481482
F1-score of SGD is: 0.30526315789473685

Confusion Matrix is :
[[512  28]
 [256  54]]

Accuracy is: 0.6658823529411765
Precison is: 0.6585365853658537
Recall is: 0.17419354838709677
F1-score of SGD is: 0.2755102040816326

Confusion Matrix is :
[[566  22]
 [211  50]]

Accuracy is: 0.7255594817432274
Precison is: 0.6944444444444444
Recall is: 0.19157088122605365
F1-score of SGD is: 0.30030030030030025

Confusion Matrix is :
[[533  22]
 [261  33]]

Accuracy is: 0.6666666666666666
Precison is: 0.6
Recall is: 0.11224489795918367
F1-score of SGD is: 0.18911174785100288

Confusion Matrix is :
[[537  19]
 [238  55]]

Accuracy is: 0.6972909305064782
Precison is: 0.7432432432432432
Recall is: 0.18771331058020477
F1-score of SGD is: 0.29972752043596723



### Multiclass

In [25]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
kf = KFold(n_splits=5)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y_multi[train_index], Y_multi[test_index]
    model = OneVsRestClassifier(SGDClassifier(alpha=0.001, penalty='l2'))
    model.fit(X_train, y_train)
    y_predicted = model.predict(X_test)
    confusionM = confusion_matrix(y_test,y_predicted )
    print("Confusion Matrix is :")
    print(confusionM)
    print()
    print("Accuracy is:",accuracy(y_test, y_predicted))
    TP = confusionM[1][1]
    TN = confusionM[0][0]
    FN = confusionM[1][0]
    FP = confusionM[0][1]
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    f1_score = 2*((precision* recall)/ (precision+recall))
    print("Precison is:", precision)
    print("Recall is:", recall)
    print("F1-score of SGD is:", f1_score)
    print()


Confusion Matrix is :
[[130  29  30  20  27]
 [ 66  19  22  23  28]
 [ 54  17  31  29  32]
 [ 59  21  26  30  17]
 [ 48  12  27  21  32]]

Accuracy is: 0.2847058823529412
Precison is: 0.3958333333333333
Recall is: 0.2235294117647059
F1-score of SGD is: 0.2857142857142857

Confusion Matrix is :
[[181  25  32   9  17]
 [110  27  27   4  21]
 [ 82  25  20   4  18]
 [ 71  21  23   3  23]
 [ 40  22  23   6  16]]

Accuracy is: 0.29058823529411765
Precison is: 0.5192307692307693
Recall is: 0.19708029197080293
F1-score of SGD is: 0.2857142857142857

Confusion Matrix is :
[[112  39  22   7  48]
 [ 66  35  26  10  34]
 [ 42  35  11   7  34]
 [ 55  47  14   7  47]
 [ 40  46  18   8  39]]

Accuracy is: 0.24028268551236748
Precison is: 0.47297297297297297
Recall is: 0.3465346534653465
F1-score of SGD is: 0.4

Confusion Matrix is :
[[132  63  12  16  18]
 [100  62  20  17  15]
 [ 50  54  24   9  24]
 [ 30  41  16  20  11]
 [ 43  33  17  12  10]]

Accuracy is: 0.2921083627797409
Precison is: 0.496
Re